# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnEngage = QtWidgets.QPushButton(self.centralwidget)
        self.btnEngage.setGeometry(QtCore.QRect(50, 120, 94, 32))
        self.btnEngage.setObjectName("btnEngage")
        self.btnNewTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewTask.setGeometry(QtCore.QRect(150, 120, 94, 32))
        self.btnNewTask.setObjectName("btnNewTask")
        self.btnViewTasks = QtWidgets.QPushButton(self.centralwidget)
        self.btnViewTasks.setGeometry(QtCore.QRect(250, 120, 94, 32))
        self.btnViewTasks.setObjectName("btnViewTasks")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(350, 120, 94, 32))
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 24))
        self.menubar.setObjectName("menubar")
        self.menuControls = QtWidgets.QMenu(self.menubar)
        self.menuControls.setObjectName("menuControls")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_engage = QtWidgets.QAction(MainWindow)
        self.act_engage.setObjectName("act_engage")
        self.act_disengage = QtWidgets.QAction(MainWindow)
        self.act_disengage.setObjectName("act_disengage")
        self.actionTags = QtWidgets.QAction(MainWindow)
        self.actionTags.setObjectName("actionTags")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionTasks = QtWidgets.QAction(MainWindow)
        self.actionTasks.setObjectName("actionTasks")
        self.menuControls.addAction(self.act_engage)
        self.menuControls.addAction(self.act_disengage)
        self.menuEdit.addAction(self.actionTasks)
        self.menuEdit.addAction(self.actionTags)
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuControls.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TaskTicker"))
        self.label.setText(_translate("MainWindow", "TaskTicker 0.1"))
        self.btnEngage.setText(_translate("MainWindow", "Engage"))
        self.btnNewTask.setText(_translate("MainWindow", "New Task"))
        self.btnViewTasks.setText(_translate("MainWindow", "View Tasks"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.menuControls.setTitle(_translate("MainWindow", "Actions"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.act_engage.setText(_translate("MainWindow", "Engage"))
        self.act_disengage.setText(_translate("MainWindow", "Disengage"))
        self.actionTags.setText(_translate("MainWindow", "Tags"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionTasks.setText(_translate("MainWindow", "Tasks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
