# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wip.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WIP(object):
    def setupUi(self, WIP):
        WIP.setObjectName("WIP")
        WIP.resize(321, 161)
        self.clbDone = QtWidgets.QCommandLinkButton(WIP)
        self.clbDone.setGeometry(QtCore.QRect(230, 120, 71, 31))
        self.clbDone.setObjectName("clbDone")
        self.label = QtWidgets.QLabel(WIP)
        self.label.setGeometry(QtCore.QRect(20, 10, 281, 51))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblTask = QtWidgets.QLabel(WIP)
        self.lblTask.setGeometry(QtCore.QRect(20, 60, 281, 51))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblTask.setFont(font)
        self.lblTask.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTask.setWordWrap(True)
        self.lblTask.setObjectName("lblTask")
        self.tolExtra = QtWidgets.QToolButton(WIP)
        self.tolExtra.setGeometry(QtCore.QRect(10, 120, 28, 30))
        self.tolExtra.setObjectName("tolExtra")

        self.retranslateUi(WIP)
        QtCore.QMetaObject.connectSlotsByName(WIP)

    def retranslateUi(self, WIP):
        _translate = QtCore.QCoreApplication.translate
        WIP.setWindowTitle(_translate("WIP", "Now Working On"))
        self.clbDone.setText(_translate("WIP", "Done!"))
        self.label.setText(_translate("WIP", "Now Working On"))
        self.lblTask.setText(_translate("WIP", "Your task here"))
        self.tolExtra.setText(_translate("WIP", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WIP = QtWidgets.QWidget()
    ui = Ui_WIP()
    ui.setupUi(WIP)
    WIP.show()
    sys.exit(app.exec_())
